// <auto-generated />
using System;
using Ejemplo_EF_Avanzado1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ejemplo_EF_Avanzado1.Data.Migrations
{
    [DbContext(typeof(EjemploEfContext))]
    [Migration("20260311194110_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ejemplo_EF_Avanzado1.Data.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LU")
                        .HasColumnType("integer")
                        .HasColumnName("lu");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Nota")
                        .HasColumnType("numeric")
                        .HasColumnName("nota");

                    b.HasKey("Id")
                        .HasName("pk_alumno");

                    b.HasIndex("LU")
                        .IsUnique()
                        .HasDatabaseName("ix_alumno_lu")
                        .HasFilter("is_deleted = false");

                    b.ToTable("alumno", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LU = 12001,
                            Nombre = "Lucas Pérez",
                            Nota = 8.5m
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LU = 12002,
                            Nombre = "Sofía Ramírez",
                            Nota = 9.0m
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LU = 12003,
                            Nombre = "Mateo González",
                            Nota = 6.5m
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LU = 12004,
                            Nombre = "Valentina López",
                            Nota = 7.0m
                        });
                });

            modelBuilder.Entity("Ejemplo_EF_Avanzado1.Data.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Entregada")
                        .HasColumnType("boolean")
                        .HasColumnName("entregada");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_tarea");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("ix_tarea_alumno_id");

                    b.ToTable("tarea", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlumnoId = 1,
                            Descripcion = "Implementar ordenamiento burbuja",
                            Entregada = true,
                            FechaEntrega = new DateOnly(2025, 4, 10),
                            IsDeleted = false,
                            Titulo = "TP1 - Algoritmos"
                        },
                        new
                        {
                            Id = 2,
                            AlumnoId = 1,
                            Descripcion = "Diseñar modelo relacional",
                            Entregada = false,
                            FechaEntrega = new DateOnly(2025, 4, 20),
                            IsDeleted = false,
                            Titulo = "TP2 - Base de Datos"
                        },
                        new
                        {
                            Id = 3,
                            AlumnoId = 2,
                            Descripcion = "Implementar ordenamiento burbuja",
                            Entregada = true,
                            FechaEntrega = new DateOnly(2025, 4, 10),
                            IsDeleted = false,
                            Titulo = "TP1 - Algoritmos"
                        },
                        new
                        {
                            Id = 4,
                            AlumnoId = 3,
                            Descripcion = "Configurar una red local",
                            Entregada = false,
                            FechaEntrega = new DateOnly(2025, 5, 1),
                            IsDeleted = false,
                            Titulo = "TP1 - Redes"
                        });
                });

            modelBuilder.Entity("Ejemplo_EF_Avanzado1.Data.Entities.Tarea", b =>
                {
                    b.HasOne("Ejemplo_EF_Avanzado1.Data.Entities.Alumno", "Alumno")
                        .WithMany("Tareas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tarea_alumno_alumno_id");

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("Ejemplo_EF_Avanzado1.Data.Entities.Alumno", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
